### ISSUE TITLE
Playlist Loader for Kodi Matrix 19

### ISSUE THREAD

**Issue by burekas7** [Silhouette2022/kodi#4]
Hi,

I modified the code and make it works on Kodi 19 and up.
See PR: https://github.com/Silhouette2022/kodi/pull/3

By the way, your repo addon also doesn't support Kodi 19.
So before add it to your repo, you should fix it too.

**Comment by Silhouette2022** [comment]
I've created new kodi 19 dedicated repo kodi.matrix and that repo has kodi 19 adopted playlistloader addon.
This one left for those who still use some older revisions of kodi

**Comment by burekas7** [comment]
@Silhouette2022 
1. Where can I get the zip file of your Matrix repo?
2. So my PR for Playlist Loader for Matrix is not needed?

**Comment by Silhouette2022** [comment]
https://github.com/Silhouette2022/kodi.matrix
The idea was to keep this repo for pre matrix builds.
I'm not sure if some platforms ever get matrix build.
You are welcome to fork and maintain this particular version if you like it better.

**Comment by burekas7** [comment]
In the version of PlaylistLoader in your Matrix repo it shows that you forked it from Publish3r.
In the ChangeLog you can't know about what of the python2 version he base his matrix version on.

As I know:
I think the original stopped development in 1.0.3 (Py2),
Then Nux stopped development in 1.3 (Py2),
Then you are development until 1.4.9 (Py2),
And my Matrix version based on your version (Py3 - Matrix).

So I guess my version should be better.

**Comment by Silhouette2022** [comment]
All my changes were related to playlist groups and EPG support for TV providers.
All that stuff is ported to kodi.matrix repo version of playlistloader.
Nux updates related for ability to include youtube links into playlists.
If you use something like that then it's useful for you.
Otherwise you won't see any difference.
